# Generated by Django 4.2.4 on 2023-08-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('written_by', models.CharField(max_length=128)),
                ('publisher', models.CharField(max_length=128)),
                ('category', models.IntegerField()),
            ],
        ),
    ]
