# Generated by Django 4.2.3 on 2023-08-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='written_by',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
