# Generated by Django 4.2.4 on 2023-09-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_written_by_book_author_rename_name_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
