# Generated by Django 4.2.5 on 2023-09-16 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_id_alter_book_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='id',
            new_name='book_code',
        ),
    ]
