# Generated by Django 4.2.4 on 2023-08-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hash_key', models.CharField(max_length=128)),
            ],
        ),
    ]
