# Generated by Django 4.2.4 on 2023-09-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hash_key',
            field=models.CharField(max_length=256),
        ),
    ]
