# Generated by Django 4.2.4 on 2023-09-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_hash_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hash_key',
            field=models.BinaryField(),
        ),
    ]
